# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 08:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_link_post_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='post_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
