# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 08:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20170210_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='post_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
