# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20170210_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='view',
            field=models.IntegerField(default=0),
        ),
    ]
