# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_link_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='up',
            field=models.IntegerField(default=0),
        ),
    ]
