# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_vote_up'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='hot',
            field=models.FloatField(default=1.0),
            preserve_default=False,
        ),
    ]
