# -*- coding: utf-8 -*-

"""
Django settings for akbnews project.

Generated by 'django-admin startproject' using Django 1.10.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""


import os
import socket
import log


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
#SECRET_KEY = '9u^3l_umg%7lbqwb$+i(=9oi#ouj5n=s)$+m%yj9k44*2#$j=h'
secret_key_path = os.path.join(BASE_DIR,'SECRET_KEY.txt')
with open(secret_key_path) as f:
    SECRET_KEY = f.read().strip()

# SECURITY WARNING: don't run with debug turned on in production!
#if socket.gethostname() == 'Lenovo':
running_space  = os.environ.get('RUNNING_SPACE', 'local')
log.logger.debug('RUNNING_SPACE: {0}'.format(running_space))
if running_space != 'DJANGO_PRODUCTION_SETTINGS':
    DEBUG = True
    log.logger.debug('DEBUG值设置为{0}所以选择的是本地环境'.format(DEBUG))
else:
    DEBUG = False
    ALLOWED_HOSTS = ['.derekning.club', 'localhost', '45.77.208.46']
    log.logger.debug('DEBUG值设置为{0}所以选择的是线上环境'.format(DEBUG))


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'news',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'akbnews.urls'


TEMPLATE_PATH = os.path.join(BASE_DIR, 'templates')


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATE_PATH,],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'akbnews.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases


if DEBUG:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'OPTIONS': {'read_default_file': os.path.join(BASE_DIR, 'local.cnf')},
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'OPTIONS': {'read_default_file': os.path.join(BASE_DIR, 'online.cnf')},
        }
    }


# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'
#LANGUAGE_CODE = 'zh-cn'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = '/static/'
if DEBUG:
    # local setting
    STATIC_PATH = os.path.join(BASE_DIR,'static')
    STATICFILES_DIRS = [STATIC_PATH,]
else:
    # server
    STATIC_ROOT = os.path.join(BASE_DIR, 'static')

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# email setting
EMAIL_HOST = 'smtp.exmail.qq.com'
EMAIL_PORT = 465
EMAIL_HOST_USER = '353268509@derekning.club'

password_path = os.path.join(BASE_DIR,'EMAIL_HOST_PASSWORD.txt')
with open(password_path) as f:
    EMAIL_HOST_PASSWORD = f.read().strip()

EMAIL_USE_TLS = False
EMAIL_USE_SSL = True
